(define (problem railway-traffic-real)
  (:domain railway-traffic)

  (:objects
    ; Treni
    train-1 train-2 train-3 - train

    ; Posizioni
    start-1 - position
    exit-1 - position

    ; Nodi point
    point-1 point-2 point-3 point-4 point-5 point-6 point-7 point-8 point-9 point-10 point-11 point-12 point-13 - position

    ; Fermate
    stop-1 stop-2 stop-3 stop-4 stop-5 stop-6 stop-7 stop-8 - stop-point

    ; Nodi switch (posizioni con scambio)
    switch-1 switch-2 switch-3 switch-4 switch-5 switch-6 switch-7 switch-8 switch-9 switch-10 switch-11 switch-12 switch-14 switch-15 switch-18 switch-19 switch-20 switch-21 switch-22 switch-25 switch-26 - switch

    ; Binari
    track-1 track-2 track-3 track-4 track-5 track-6 track-7 track-8 track-16 track-17 track-18 track-19 track-20 track-21 track-22 track-23 track-24 track-27 track-28 track-29 track-30 track-31 track-32 track-33 track-34 track-35 track-36 track-51 track-52 track-53 track-54 track-55 track-56 - track

  )

  (:init
    ; Posizioni iniziali dei treni
    (train-at train-1 start-1)
    (train-at train-2 start-1)
    (train-at train-3 start-1)

    ; Autorizzazioni di partenza
    (can-start train-1)
    (can-start train-2)
    (can-start train-3)

    ; Assegnazione fermata per ogni treno
    (train-assigned-stop train-1 stop-6)
    (train-assigned-stop train-2 stop-7)
    (train-assigned-stop train-3 stop-8)

     ;; Configurazione della rete ferroviaria
    ; (connected point-10 stop-1 track-1)           (connected stop-1 point-10 track-1)
    ; (connected point-11 stop-2 track-2)           (connected stop-2 point-11 track-2)
    ; (connected switch-26 stop-3 track-3)          (connected stop-3 switch-26 track-3)
    ; (connected switch-26 point-11 track-52)       (connected point-11 switch-26 track-52)
    ; (connected switch-25 switch-26 track-53)      (connected switch-26 switch-25 track-53)
    (connected point-7 switch-25 track-54)        (connected switch-25 point-7 track-54)
    (connected point-10 switch-25 track-51)       (connected switch-25 point-10 track-51)
    ; (connected switch-21 point-7 track-55)        (connected point-7 switch-21 track-55)
    (connected switch-21 switch-22 track-56)      (connected switch-22 switch-21 track-56)
    (connected point-12 stop-4 track-4)           (connected stop-4 point-12 track-4)
    (connected switch-22 stop-5 track-5)          (connected stop-5 switch-22 track-5)
    (connected switch-7 stop-6 track-6)           (connected stop-6 switch-7 track-6)
    (connected switch-6 switch-7 track-18)        (connected switch-7 switch-6 track-18)
    (connected switch-7 switch-11 track-19)       (connected switch-11 switch-7 track-19)
    (connected switch-12 stop-7 track-7)          (connected stop-7 switch-12 track-7)
    (connected point-13 stop-8 track-8)           (connected stop-8 point-13 track-8)
    (connected switch-12 point-13 track-22)       (connected point-13 switch-12 track-22)
    (connected switch-11 switch-12 track-21)      (connected switch-12 switch-11 track-21)
    (connected switch-10 switch-11 track-23)      (connected switch-11 switch-10 track-23)
    (connected switch-3 switch-4 track-28)        (connected switch-4 switch-3 track-28)
    (connected switch-9 switch-10 track-29)       (connected switch-10 switch-9 track-29)
    (connected switch-4 switch-10 track-27)       (connected switch-10 switch-4 track-27)
    (connected switch-5 switch-6 track-20)        (connected switch-6 switch-5 track-20)
    (connected switch-4 switch-5 track-24)        (connected switch-5 switch-4 track-24)
    ; (connected switch-20 switch-21 track-16)      (connected switch-21 switch-20 track-16)
    ; (connected point-6 switch-20 track-26)        (connected switch-20 point-6 track-26)
    (connected switch-6 switch-21 track-17)       (connected switch-21 switch-6 track-17)
    ; (connected switch-5 switch-20 track-25)       (connected switch-20 switch-5 track-25)
    ; (connected point-5 point-6 track-50)          (connected point-6 point-5 track-50)
    ; (connected switch-19 point-5 track-49)        (connected point-5 switch-19 track-49)
    ; (connected switch-14 switch-19 track-46)      (connected switch-19 switch-14 track-46)
    ; (connected switch-15 switch-18 track-45)      (connected switch-18 switch-15 track-45)
    ; (connected point-8 point-9 track-44)          (connected point-9 point-8 track-44)
    ; (connected switch-19 switch-18 track-48)      (connected switch-18 switch-19 track-48)
    ; (connected switch-18 point-9 track-47)        (connected point-9 switch-18 track-47)
    ; (connected switch-15 point-8 track-43)        (connected point-8 switch-15 track-43)
    ; (connected switch-14 switch-15 track-42)      (connected switch-15 switch-14 track-42)
    ; (connected point-4 switch-14 track-41)        (connected switch-14 point-4 track-41)
    ; (connected point-3 point-4 track-40)        (connected point-4 point-3 track-40)
    ; (connected point-2 point-3 track-39)          (connected point-3 point-2 track-39)
    ; (connected point-1 point-2 track-38)          (connected point-2 point-1 track-38)
    ; (connected switch-2 point-1 track-37)         (connected point-1 switch-2 track-37)
    (connected switch-2 switch-3 track-31)        (connected switch-3 switch-2 track-31)
    (connected switch-1 switch-2 track-32)        (connected switch-2 switch-1 track-32)
    (connected start-1 switch-1  track-35)        (connected switch-1 start-1 track-35)
    (connected switch-8 switch-9 track-33)        (connected switch-9 switch-8 track-33)
    (connected exit-1 switch-8 track-36)          (connected switch-8 exit-1 track-36)
    (connected switch-9 switch-3 track-30)        (connected switch-3 switch-9 track-30)
    (connected switch-8 switch-1 track-34)        (connected switch-1 switch-8 track-34)



   ;; Percorsi alternativi per gli switch
    (switch-path switch-25 track-54 track-53)
    (switch-path switch-25 track-53 track-54)
    (switch-path switch-25 track-54 track-51)
    (switch-path switch-25 track-51 track-54)
    ; (switch-path switch-26 track-53 track-3)
    ; (switch-path switch-26 track-3 track-53)
    ; (switch-path switch-26 track-53 track-52)
    ; (switch-path switch-26 track-52 track-53)
    (switch-path switch-22 track-56 track-5)
    (switch-path switch-22 track-5 track-56)
    (switch-path switch-22 track-56 track-54)
    (switch-path switch-22 track-54 track-56)
    (switch-path switch-21 track-16 track-56)
    (switch-path switch-21 track-56 track-16)
    ; (switch-path switch-21 track-16 track-55)
    ; (switch-path switch-21 track-55 track-16)
    (switch-path switch-21 track-56 track-17)
    (switch-path switch-21 track-17 track-56)
    ; (switch-path switch-21 track-55 track-17)
    ; (switch-path switch-21 track-17 track-55)
    (switch-path switch-6 track-20 track-18)
    (switch-path switch-6 track-18 track-20)
    (switch-path switch-6 track-20 track-17)
    (switch-path switch-6 track-17 track-20)
    (switch-path switch-11 track-23 track-21)
    (switch-path switch-11 track-21 track-23)
    (switch-path switch-11 track-19 track-21)
    (switch-path switch-11 track-21 track-19)
    (switch-path switch-12 track-21 track-7)
    (switch-path switch-12 track-7 track-21)
    (switch-path switch-12 track-21 track-22)
    (switch-path switch-12 track-22 track-21)
    (switch-path switch-7 track-18 track-6)
    (switch-path switch-7 track-6 track-18)
    (switch-path switch-7 track-18 track-19)
    (switch-path switch-7 track-19 track-18)
    (switch-path switch-5 track-24 track-20)
    (switch-path switch-5 track-20 track-24)
    ; (switch-path switch-5 track-25 track-20)
    ; (switch-path switch-5 track-20 track-25)
    ; (switch-path switch-20 track-26 track-16)
    ; (switch-path switch-20 track-16 track-26)
    ; (switch-path switch-20 track-26 track-25)
    ; (switch-path switch-20 track-25 track-26)
    (switch-path switch-4 track-28 track-24)
    (switch-path switch-4 track-24 track-28)
    (switch-path switch-4 track-24 track-27)
    (switch-path switch-4 track-27 track-24)
    (switch-path switch-10 track-29 track-23)
    (switch-path switch-10 track-23 track-29)
    (switch-path switch-10 track-29 track-27)
    (switch-path switch-10 track-27 track-29)
    ; (switch-path switch-19 track-46 track-49)
    ; (switch-path switch-19 track-49 track-46)
    ; (switch-path switch-19 track-48 track-49)
    ; (switch-path switch-19 track-49 track-48)
    ; (switch-path switch-18 track-45 track-48)
    ; (switch-path switch-18 track-48 track-45)
    ; (switch-path switch-18 track-47 track-48)
    ; (switch-path switch-18 track-48 track-47)
    ; (switch-path switch-15 track-42 track-45)
    ; (switch-path switch-15 track-45 track-42)
    ; (switch-path switch-15 track-42 track-43)
    ; (switch-path switch-15 track-43 track-42)
    ; (switch-path switch-14 track-41 track-46)
    ; (switch-path switch-14 track-46 track-41)
    ; (switch-path switch-14 track-41 track-42)
    ; (switch-path switch-14 track-42 track-41)
    (switch-path switch-2 track-32 track-31)
    (switch-path switch-2 track-31 track-32)
    ; (switch-path switch-2 track-37 track-32)
    ; (switch-path switch-2 track-32 track-37)
    (switch-path switch-3 track-31 track-28)
    (switch-path switch-3 track-28 track-31)
    (switch-path switch-3 track-31 track-30)
    (switch-path switch-3 track-30 track-31)
    (switch-path switch-9 track-33 track-29)
    (switch-path switch-9 track-29 track-33)
    (switch-path switch-9 track-30 track-29)
    (switch-path switch-9 track-29 track-30)
    (switch-path switch-1 track-35 track-32)
    (switch-path switch-1 track-32 track-35)
    (switch-path switch-1 track-32 track-34)
    (switch-path switch-1 track-34 track-32)
    (switch-path switch-8 track-36 track-33)
    (switch-path switch-8 track-33 track-36)
    (switch-path switch-8 track-36 track-34)
    (switch-path switch-8 track-34 track-36)

    ;; Occupazione iniziale degli switch
    (switch-status switch-25 track-54 track-53)
    (switch-status switch-25 track-53 track-54)
    ; (switch-status switch-26 track-53 track-3)
    ; (switch-status switch-26 track-3 track-53)
    (switch-status switch-22 track-56 track-5)
    (switch-status switch-22 track-5 track-56)
    (switch-status switch-21 track-16 track-56)
    (switch-status switch-21 track-56 track-16)
    (switch-status switch-6 track-20 track-18)
    (switch-status switch-6 track-18 track-20)
    (switch-status switch-11 track-23 track-21)
    (switch-status switch-11 track-21 track-23)
    (switch-status switch-12 track-21 track-7)
    (switch-status switch-12 track-7 track-21)
    (switch-status switch-7 track-18 track-6)
    (switch-status switch-7 track-6 track-18)
    (switch-status switch-5 track-24 track-20)
    (switch-status switch-5 track-20 track-24)
    ; (switch-status switch-20 track-26 track-16)
    ; (switch-status switch-20 track-16 track-26)
    (switch-status switch-4 track-28 track-24)
    (switch-status switch-4 track-24 track-28)
    (switch-status switch-10 track-29 track-23)
    (switch-status switch-10 track-23 track-29)
    ; (switch-status switch-19 track-46 track-49)
    ; (switch-status switch-19 track-49 track-46)
    ; (switch-status switch-18 track-45 track-48)
    ; (switch-status switch-18 track-48 track-45)
    ; (switch-status switch-15 track-42 track-45)
    ; (switch-status switch-15 track-45 track-42)
    ; (switch-status switch-14 track-41 track-46)
    ; (switch-status switch-14 track-46 track-41)
    (switch-status switch-2 track-32 track-31)
    (switch-status switch-2 track-31 track-32)
    (switch-status switch-3 track-31 track-28)
    (switch-status switch-3 track-28 track-31)
    (switch-status switch-9 track-33 track-29)
    (switch-status switch-9 track-29 track-33)
    (switch-status switch-1 track-35 track-32)
    (switch-status switch-1 track-32 track-35)
    (switch-status switch-8 track-36 track-33)
    (switch-status switch-8 track-33 track-36)

    ; Tutti i binari sono inizialmente liberi
    ; (not (track-occupied track-1))
    ; (not (track-occupied track-2))
    ; (not (track-occupied track-3))
    ; (not (track-occupied track-52))
    ; (not (track-occupied track-53))
    (not (track-occupied track-54))
    ; (not (track-occupied track-51))
    ; (not (track-occupied track-55))
    (not (track-occupied track-56))
    (not (track-occupied track-4))
    (not (track-occupied track-5))
    (not (track-occupied track-6))
    (not (track-occupied track-18))
    (not (track-occupied track-19))
    (not (track-occupied track-7))
    (not (track-occupied track-8))
    (not (track-occupied track-22))
    (not (track-occupied track-21))
    (not (track-occupied track-23))
    (not (track-occupied track-28))
    (not (track-occupied track-29))
    (not (track-occupied track-27))
    (not (track-occupied track-20))
    (not (track-occupied track-24))
    ; (not (track-occupied track-16))
    ; (not (track-occupied track-26))
    (not (track-occupied track-17))
    ; (not (track-occupied track-25))
    ; (not (track-occupied track-50))
    ; (not (track-occupied track-49))
    ; (not (track-occupied track-46))
    ; (not (track-occupied track-45))
    ; (not (track-occupied track-44))
    ; (not (track-occupied track-48))
    ; (not (track-occupied track-47))
    ; (not (track-occupied track-43))
    ; (not (track-occupied track-42))
    ; (not (track-occupied track-41))
    ; (not (track-occupied track-40))
    ; (not (track-occupied track-39))
    ; (not (track-occupied track-38))
    ; (not (track-occupied track-37))
    (not (track-occupied track-31))
    (not (track-occupied track-32))
    (not (track-occupied track-35))
    (not (track-occupied track-33))
    (not (track-occupied track-36))
    (not (track-occupied track-30))
    (not (track-occupied track-34))


    ;; Tempi di percorrenza (in secondi)
    ; (= (travel-time track-1) 8)
    ; (= (travel-time track-2) 8)
    ; (= (travel-time track-3) 10)
    ; (= (travel-time track-52) 12)
    ; (= (travel-time track-53) 6)
    (= (travel-time track-54) 15)
    ; (= (travel-time track-51) 20)
    ; (= (travel-time track-55) 12)
    (= (travel-time track-56) 8)
    (= (travel-time track-4) 10)
    (= (travel-time track-5) 7)
    (= (travel-time track-6) 9)
    (= (travel-time track-18) 6)
    (= (travel-time track-19) 8)
    (= (travel-time track-7) 8)
    (= (travel-time track-8) 10)
    (= (travel-time track-22) 12)
    (= (travel-time track-21) 7)
    (= (travel-time track-23) 9)
    (= (travel-time track-28) 5)
    (= (travel-time track-29) 11)
    (= (travel-time track-27) 10)
    (= (travel-time track-20) 6)
    (= (travel-time track-24) 5)
    ; (= (travel-time track-16) 14)
    ; (= (travel-time track-26) 18)
    (= (travel-time track-17) 16)
    ; (= (travel-time track-25) 13)
    ; (= (travel-time track-50) 25)
    ; (= (travel-time track-49) 20)
    ; (= (travel-time track-46) 15)
    ; (= (travel-time track-45) 12)
    ; (= (travel-time track-44) 22)
    ; (= (travel-time track-48) 8)
    ; (= (travel-time track-47) 18)
    ; (= (travel-time track-43) 14)
    ; (= (travel-time track-42) 10)
    ; (= (travel-time track-41) 16)
    ; (= (travel-time track-40) 10)
    ; (= (travel-time track-39) 20)
    ; (= (travel-time track-38) 15)
    ; (= (travel-time track-37) 12)
    (= (travel-time track-31) 5)
    (= (travel-time track-32) 6)
    (= (travel-time track-35) 8)
    (= (travel-time track-33) 7)
    (= (travel-time track-36) 9)
    (= (travel-time track-30) 11)
    (= (travel-time track-34) 7)

    ; Tempo iniziale del sistema
    (= (current-time) 0)
    (= (switch-changes) 0)
    (= (total-actions) 0)


    ; Sistema inizializzato
    (system-initialized)
  )

  (:goal
    (and
      ; Tutti i treni devono raggiungere exit-1
      (train-at train-1 exit-1)
      (train-at train-2 exit-1)
      (train-at train-3 exit-1)

      ; Ogni treno deve aver completato la sosta alla sua fermata assegnata
      (completed-stop train-1 stop-6)
      (completed-stop train-2 stop-7)
      (completed-stop train-3 stop-8)
    )
  )

  ; Obiettivo con penalità
  (:metric minimize (+ (*0.9(total-time))
                        (* 0.9 (total-actions))))

)
